#ifndef _EEPROM_H_
#define _EEPROM_H_

// Structures and defines
typedef enum {
    EEPADDR_CALIB_BATT_VOLTAGE_POINT_1_RAW = 0,
    EEPADDR_CALIB_BATT_VOLTAGE_POINT_1_PHYS_mV,
    EEPADDR_CALIB_BATT_VOLTAGE_POINT_2_RAW,
    EEPADDR_CALIB_BATT_VOLTAGE_POINT_2_PHYS_mV,
    
    EEPADDR_CALIB_GLOBAL_CURRENT_POINT_1_RAW,
    EEPADDR_CALIB_GLOBAL_CURRENT_POINT_1_PHYS_mA,
    EEPADDR_CALIB_GLOBAL_CURRENT_POINT_2_RAW,
    EEPADDR_CALIB_GLOBAL_CURRENT_POINT_2_PHYS_mA,

    EEPADDR_CALIB_CURRENT_OUT1_POINT_1_RAW,
    EEPADDR_CALIB_CURRENT_OUT1_POINT_1_PHYS_mA,
    EEPADDR_CALIB_CURRENT_OUT1_POINT_2_RAW,
    EEPADDR_CALIB_CURRENT_OUT1_POINT_2_PHYS_mA,
            
    EEPADDR_CALIB_CURRENT_OUT2_POINT_1_RAW,
    EEPADDR_CALIB_CURRENT_OUT2_POINT_1_PHYS_mA,
    EEPADDR_CALIB_CURRENT_OUT2_POINT_2_RAW,
    EEPADDR_CALIB_CURRENT_OUT2_POINT_2_PHYS_mA,

    // _________
    EEPADDR_MAGIC_NUMBER,
    EEPROM_SIZE
}tEEPROM_addresses;

#define EEPROM_MAGIC_NUMBER (0x5A96)
#define EEPROM_WRITE_UNPROTECT (0x5A)

// Functions prototypes
void Init_EEPROM(); 
void readEEPROM();
void saveEEPROM();
void forceEEPROMDefaultValues();

// External data
extern unsigned short EEPROM_values[];




#endif // _EEPROM_H_
